swagger: '2.0'
info:
  title: Swaggy Jenkins
  description: Jenkins remote access API
  version: "0.0.1"
  contact:
    name: Cliffano Subagio
    url: http://github.com/cliffano/swaggy-jenkins
    email: blah@cliffano.com
schemes:
  - http
  - https
basePath: /
securityDefinitions:
  jenkins_auth:
    type: basic
paths:
  /:
    head:
      description: Retrieve version header
      operationId: headVersion
      responses:
        200:
          description: Successfully retrieved version
          headers:
            x-jenkins:
              type: string
      tags:
        - jenkins
  /api/json:
    get:
      description: Get info
      operationId: getInfo
      produces:
        - application/json
      responses:
        200:
          description: Successfully get info
          schema:
            $ref: "#/definitions/hudsonmodelHudson"
        401:
          $ref: "#/responses/unauthorized"
        403:
          $ref: "#/responses/forbidden"
      tags:
        - jenkins
  /computer/api/json?depth=1:
    get:
      description: Get computer
      operationId: getComputer
      produces:
        - application/json
      responses:
        200:
          description: Successfully get computer
          schema:
            $ref: "#/definitions/hudsonmodelComputerSet"
        401:
          $ref: "#/responses/unauthorized"
        403:
          $ref: "#/responses/forbidden"
      tags:
        - jenkins
  /crumbIssuer/api/json:
    get:
      description: Get crumb
      operationId: getCrumb
      produces:
        - application/json
      responses:
        200:
          description: Successfully get crumb
          schema:
            $ref: "#/definitions/hudsonsecuritycsrfDefaultCrumbIssuer"
      tags:
        - jenkins
  /queue/api/json:
    get:
      description: Get queue
      operationId: getQueue
      produces:
        - application/json
      responses:
        200:
          description: Successfully get queue
          schema:
            $ref: "#/definitions/hudsonmodelQueue"
      tags:
        - jenkins
responses:
  unauthorized:
    description: Authentication failed - incorrect username and/or password
  forbidden:
    description: Jenkins requires authentication - please set username and password
definitions:
  hudsonmodelFreeStyleBuild:
    type: object
    properties:
      _class:
        type: string
      number:
        type: integer
      url:
        type: string
  hudsonmodelHudsonMasterComputerexecutors:
    type: object
    properties:
      currentExecutable:
        $ref: '#/definitions/hudsonmodelFreeStyleBuild'
      idle:
        type: boolean
      likelyStuck:
        type: boolean
      number:
        type: integer
      progress:
        type: integer
      _class:
        type: string
  hudsonmodelLabel1:
    type: object
    properties:
      _class:
        type: string
  hudsonnode_monitorsSwapSpaceMonitorMemoryUsage2:
    type: object
    properties:
      _class:
        type: string
      availablePhysicalMemory:
        type: integer
      availableSwapSpace:
        type: integer
      totalPhysicalMemory:
        type: integer
      totalSwapSpace:
        type: integer
  hudsonnode_monitorsDiskSpaceMonitorDescriptorDiskSpace:
    type: object
    properties:
      _class:
        type: string
      timestamp:
        type: integer
      path:
        type: string
      size:
        type: integer
  hudsonnode_monitorsResponseTimeMonitorData:
    type: object
    properties:
      _class:
        type: string
      timestamp:
        type: integer
      average:
        type: integer
  hudsonutilClockDifference:
    type: object
    properties:
      _class:
        type: string
      diff:
        type: integer
  hudsonmodelHudsonMasterComputer_monitorData:
    type: object
    properties:
      hudson.node_monitors.SwapSpaceMonitor:
        $ref: '#/definitions/hudsonnode_monitorsSwapSpaceMonitorMemoryUsage2'
      hudson.node_monitors.TemporarySpaceMonitor:
        $ref: '#/definitions/hudsonnode_monitorsDiskSpaceMonitorDescriptorDiskSpace'
      hudson.node_monitors.DiskSpaceMonitor:
        $ref: '#/definitions/hudsonnode_monitorsDiskSpaceMonitorDescriptorDiskSpace'
      hudson.node_monitors.ArchitectureMonitor:
        type: string
      hudson.node_monitors.ResponseTimeMonitor:
        $ref: '#/definitions/hudsonnode_monitorsResponseTimeMonitorData'
      hudson.node_monitors.ClockMonitor:
        $ref: '#/definitions/hudsonutilClockDifference'
      _class:
        type: string
  hudsonmodelHudsonMasterComputer:
    type: object
    properties:
      _class:
        type: string
      displayName:
        type: string
      executors:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelHudsonMasterComputerexecutors'
      icon:
        type: string
      iconClassName:
        type: string
      idle:
        type: boolean
      jnlpAgent:
        type: boolean
      launchSupported:
        type: boolean
      loadStatistics:
        $ref: '#/definitions/hudsonmodelLabel1'
      manualLaunchAllowed:
        type: boolean
      monitorData:
        $ref: '#/definitions/hudsonmodelHudsonMasterComputer_monitorData'
      numExecutors:
        type: integer
      offline:
        type: boolean
      offlineCause:
        type: string
      offlineCauseReason:
        type: string
      temporarilyOffline:
        type: boolean
  hudsonmodelComputerSet:
    type: object
    properties:
      _class:
        type: string
      busyExecutors:
        type: integer
      computer:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelHudsonMasterComputer'
      displayName:
        type: string
      totalExecutors:
        type: integer
  hudsonsecuritycsrfDefaultCrumbIssuer:
    type: object
    properties:
      _class:
        type: string
      crumb:
        type: string
      crumbRequestField:
        type: string
  hudsonmodelHudsonassignedLabels:
    type: object
    properties:
      _class:
        type: string
  hudsonmodelFreeStyleProject:
    type: object
    properties:
      _class:
        type: string
      name:
        type: string
      url:
        type: string
      color:
        type: string
  hudsonmodelAllView:
    type: object
    properties:
      _class:
        type: string
      name:
        type: string
      url:
        type: string
  jenkinsmodelUnlabeledLoadStatistics:
    type: object
    properties:
      _class:
        type: string
  hudsonmodelHudson:
    type: object
    properties:
      _class:
        type: string
      assignedLabels:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelHudsonassignedLabels'
      mode:
        type: string
      nodeDescription:
        type: string
      nodeName:
        type: string
      numExecutors:
        type: integer
      description:
        type: string
      jobs:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelFreeStyleProject'
      primaryView:
        $ref: '#/definitions/hudsonmodelAllView'
      quietingDown:
        type: boolean
      slaveAgentPort:
        type: integer
      unlabeledLoad:
        $ref: '#/definitions/jenkinsmodelUnlabeledLoadStatistics'
      useCrumbs:
        type: boolean
      useSecurity:
        type: boolean
      views:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelAllView'
  hudsonmodelCauseUserIdCause:
    type: object
    properties:
      _class:
        type: string
      shortDescription:
        type: string
      userId:
        type: string
      userName:
        type: string
  hudsonmodelCauseAction:
    type: object
    properties:
      _class:
        type: string
      causes:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelCauseUserIdCause'
  hudsonmodelQueueBlockedItem:
    type: object
    properties:
      _class:
        type: string
      actions:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelCauseAction'
      blocked:
        type: boolean
      buildable:
        type: boolean
      id:
        type: integer
      inQueueSince:
        type: integer
      params:
        type: string
      stuck:
        type: boolean
      task:
        $ref: '#/definitions/hudsonmodelFreeStyleProject'
      url:
        type: string
      why:
        type: string
      buildableStartMilliseconds:
        type: integer
  hudsonmodelQueue:
    type: object
    properties:
      _class:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/hudsonmodelQueueBlockedItem'
