name: OpenAPIClient
targets:
  OpenAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [OpenAPIClient]
    info:
      path: ./Info.plist
      version: 2.0.1-pre.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
