name: Publish API Documentation
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bootprint bootprint-openapi gh-pages
      - run: make doc-version
      - run: >-
          CACHE_DIR=/tmp gh-pages --dist doc/ --user "pakkunbot
          <blah+pakkun@cliffano.com>" --repo "https://cliffano:${{ secrets.STUDIO_GITHUB_TOKEN
          }}@github.com/cliffano/swaggy-jenkins.git"
